{
  parserUtilClass="net.alliedmods.intellij.sourcepawn.parser.SourcePawnParserUtils"

  tokens=[
    preprocessor_directive='regexp:#(([^\\\r\n])|(\\\h*(\r|\n|\r\n)))*(\r|\n|\r\n)'
  ]
}

root ::= root_item *
private root_item ::= !<<eof>> preprocessor
private preprocessor ::= preprocessor_directive